/* Generated By:JavaCC: Do not edit this line. PS2TokenizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PS2TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int OPERATOR = 6;
  /** RegularExpression Id. */
  int PUNCTUATION = 7;
  /** RegularExpression Id. */
  int EMAIL = 8;
  /** RegularExpression Id. */
  int DOMAIN = 9;
  /** RegularExpression Id. */
  int PHONE_NUMBER = 10;
  /** RegularExpression Id. */
  int EQUATION = 11;
  /** RegularExpression Id. */
  int WORD3 = 12;
  /** RegularExpression Id. */
  int WORD2 = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int MISC = 16;
  /** RegularExpression Id. */
  int WORD4 = 17;
  /** RegularExpression Id. */
  int MISC_SP = 18;
  /** RegularExpression Id. */
  int PRE = 20;
  /** RegularExpression Id. */
  int CLOSETAG = 21;
  /** RegularExpression Id. */
  int STYLETAG = 23;
  /** RegularExpression Id. */
  int OPENTAG = 24;
  /** RegularExpression Id. */
  int CLOSETAG_STYLE = 26;
  /** RegularExpression Id. */
  int CLOSE_PRE = 28;
  /** RegularExpression Id. */
  int MISC_PRE = 29;
  /** RegularExpression Id. */
  int WORD_PRE = 30;
  /** RegularExpression Id. */
  int FUNCTION = 31;
  /** RegularExpression Id. */
  int ASSIGNMENT = 32;
  /** RegularExpression Id. */
  int COND = 33;
  /** RegularExpression Id. */
  int SPEC = 35;
  /** RegularExpression Id. */
  int LINK = 36;
  /** RegularExpression Id. */
  int EMAIL_QT = 38;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int SPECIAL_WORD = 1;
  /** Lexical state. */
  int IN_HTML = 2;
  /** Lexical state. */
  int IN_STYLE = 3;
  /** Lexical state. */
  int IN_PRE = 4;
  /** Lexical state. */
  int IN_HTML_QUOTE = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<token of kind 2>",
    "\"\\r\"",
    "\"\\n\"",
    "\"<\"",
    "<OPERATOR>",
    "<PUNCTUATION>",
    "<EMAIL>",
    "<DOMAIN>",
    "<PHONE_NUMBER>",
    "<EQUATION>",
    "<WORD3>",
    "<WORD2>",
    "<WORD>",
    "<NUMBER>",
    "<MISC>",
    "<WORD4>",
    "<MISC_SP>",
    "\">\"",
    "<PRE>",
    "<CLOSETAG>",
    "<token of kind 22>",
    "\"style\"",
    "<OPENTAG>",
    "<token of kind 25>",
    "<CLOSETAG_STYLE>",
    "<token of kind 27>",
    "<CLOSE_PRE>",
    "<MISC_PRE>",
    "<WORD_PRE>",
    "<FUNCTION>",
    "<ASSIGNMENT>",
    "<COND>",
    "\"\\\"\"",
    "<SPEC>",
    "<LINK>",
    "<token of kind 37>",
    "<EMAIL_QT>",
  };

}
